edition = "2021"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
force_multiline_blocks = true
format_strings = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
imports_layout = "Vertical"
